DELETE http://localhost:3003/api/blogs/6992e81d9aca826956329d01
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZXhhMTgxODAiLCJpZCI6IjY5OTE5ZmYzODMzYzUyZTM2Mjk5ZTNmNSIsImlhdCI6MTc3MTIzNTM0MCwiZXhwIjoxNzcxMjM4OTQwfQ._MDo-OOYzvCdR2ASP-tfkFYvJcfGct4rjeEx5K_N7ac